"""Init

Revision ID: ad85a401a8bc
Revises: 
Create Date: 2026-07-01 08:23:26.485671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ad85a401a8bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configurators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vertical_key', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vertical_key')
    )
    op.create_table('data_feeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feed_key', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('mode', sa.Enum('stream', 'batch', name='feed_mode'), nullable=False),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_key')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('environment_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feed_key', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('impact_hint', sa.Integer(), nullable=True),
    sa.Column('happened_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('impact_hint BETWEEN 1 AND 5', name='ck_environment_events_impact_hint'),
    sa.ForeignKeyConstraint(['feed_key'], ['data_feeds.feed_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_env_events_cat_date', 'environment_events', ['category', 'happened_at'], unique=False)
    op.create_table('failure_cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vertical_key', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('risk_type', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('qdrant_point_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vertical_key'], ['configurators.vertical_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_failure_cases_risk', 'failure_cases', ['risk_type'], unique=False)
    op.create_index('idx_failure_cases_vertical', 'failure_cases', ['vertical_key'], unique=False)
    op.create_table('industry_benchmarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vertical_key', sa.Text(), nullable=False),
    sa.Column('metric_key', sa.Text(), nullable=False),
    sa.Column('segment', sa.Text(), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vertical_key'], ['configurators.vertical_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_benchmarks_vertical', 'industry_benchmarks', ['vertical_key'], unique=False)
    op.create_table('macro_indicators',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feed_key', sa.Text(), nullable=False),
    sa.Column('indicator', sa.Text(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('observed_at', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['feed_key'], ['data_feeds.feed_key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator', 'observed_at', name='uq_macro_indicator_observed_at')
    )
    op.create_index('idx_macro_indicator_date', 'macro_indicators', ['indicator', 'observed_at'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('vertical_key', sa.Text(), server_default='it_startup', nullable=False),
    sa.Column('stage', sa.Enum('idea', 'mvp', 'early_revenue', 'growth', name='project_stage'), server_default='idea', nullable=False),
    sa.Column('risk_appetite', sa.Enum('conservative', 'balanced', 'aggressive', name='risk_appetite'), server_default='balanced', nullable=False),
    sa.Column('team_size', sa.Integer(), nullable=True),
    sa.Column('runway_months', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('geography', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_projects_user', 'projects', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'analyzed', 'acted', 'closed', name='session_status'), server_default='draft', nullable=False),
    sa.Column('parent_bet_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_bet_id'], ['bets.id'], name='fk_sessions_parent_bet', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sessions_project', 'sessions', ['project_id'], unique=False)
    op.create_table('bets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('size_money', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('predicted_metric', sa.Text(), nullable=True),
    sa.Column('predicted_value', sa.Numeric(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actual_value', sa.Numeric(), nullable=True),
    sa.Column('actual_spent', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('anomaly_note', sa.Text(), nullable=True),
    sa.Column('result_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bets_project', 'bets', ['project_id'], unique=False)
    op.create_index('idx_bets_session', 'bets', ['session_id'], unique=False)
    op.create_table('env_scenarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('shock_class', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=True),
    sa.Column('likelihood', sa.Numeric(), nullable=True),
    sa.Column('source_refs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('likelihood BETWEEN 0 AND 1', name='ck_env_scenarios_likelihood'),
    sa.CheckConstraint('severity BETWEEN 1 AND 5', name='ck_env_scenarios_severity'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_env_session', 'env_scenarios', ['session_id'], unique=False)
    op.create_table('intents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('invest_money', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('invest_effort', sa.Numeric(precision=8, scale=1), nullable=True),
    sa.Column('horizon_months', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('session_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.Enum('environment', 'destructor', name='agent_kind'), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_logs_session', 'session_logs', ['session_id', 'created_at'], unique=False)
    op.create_table('threshold_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('reversibility', sa.Enum('cheap_reversible', 'costly_reversible', 'costly_irreversible', name='reversibility'), nullable=False),
    sa.Column('verdict', sa.Enum('scale', 'hold', 'exit', 'probe', name='threshold_verdict'), nullable=False),
    sa.Column('recommended_step', sa.Text(), nullable=True),
    sa.Column('step_budget', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('trust_level', sa.Numeric(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('trust_level BETWEEN 0 AND 1', name='ck_threshold_trust_level'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('assumptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('intent_id', sa.UUID(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('is_explicit', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('criticality', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('criticality BETWEEN 1 AND 5', name='ck_assumptions_criticality'),
    sa.ForeignKeyConstraint(['intent_id'], ['intents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assumptions_intent', 'assumptions', ['intent_id'], unique=False)
    op.create_table('calibration_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bet_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('predicted_value', sa.Numeric(), nullable=True),
    sa.Column('actual_value', sa.Numeric(), nullable=True),
    sa.Column('error_abs', sa.Numeric(), nullable=True),
    sa.Column('error_rel', sa.Numeric(), nullable=True),
    sa.Column('optimism_bias', sa.Numeric(), nullable=True),
    sa.Column('trust_delta', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bet_id'], ['bets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bet_id')
    )
    op.create_index('idx_calibration_project', 'calibration_records', ['project_id'], unique=False)
    op.create_table('attacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('assumption_id', sa.UUID(), nullable=True),
    sa.Column('scenario_id', sa.UUID(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('failure_point', sa.Text(), nullable=True),
    sa.Column('est_loss_money', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('survivable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assumption_id'], ['assumptions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['env_scenarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attacks_session', 'attacks', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_attacks_session', table_name='attacks')
    op.drop_table('attacks')
    op.drop_index('idx_calibration_project', table_name='calibration_records')
    op.drop_table('calibration_records')
    op.drop_index('idx_assumptions_intent', table_name='assumptions')
    op.drop_table('assumptions')
    op.drop_table('threshold_decisions')
    op.drop_index('idx_session_logs_session', table_name='session_logs')
    op.drop_table('session_logs')
    op.drop_table('intents')
    op.drop_index('idx_env_session', table_name='env_scenarios')
    op.drop_table('env_scenarios')
    op.drop_index('idx_bets_session', table_name='bets')
    op.drop_index('idx_bets_project', table_name='bets')
    op.drop_table('bets')
    op.drop_index('idx_sessions_project', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('idx_projects_user', table_name='projects')
    op.drop_table('projects')
    op.drop_index('idx_macro_indicator_date', table_name='macro_indicators')
    op.drop_table('macro_indicators')
    op.drop_index('idx_benchmarks_vertical', table_name='industry_benchmarks')
    op.drop_table('industry_benchmarks')
    op.drop_index('idx_failure_cases_vertical', table_name='failure_cases')
    op.drop_index('idx_failure_cases_risk', table_name='failure_cases')
    op.drop_table('failure_cases')
    op.drop_index('idx_env_events_cat_date', table_name='environment_events')
    op.drop_table('environment_events')
    op.drop_table('users')
    op.drop_table('data_feeds')
    op.drop_table('configurators')
    # ### end Alembic commands ###
